import assert from 'node:assert/strict';
import {buildForecast} from '../netlify/functions/_lib/forecast-engine.mjs';
import {deriveIntradayFeatures,metaAdjustment,metaFeatureVector,deriveSignalScales} from '../netlify/functions/_lib/state-logic.mjs';
import {parseUDFHistory,hourlyToLockAnchors,parseWallexDepth,parseWallexTrades,parseNobitexTrades} from '../netlify/functions/_lib/sources.mjs';

const udf=parseUDFHistory({s:'ok',t:[1788000000,1788003600],c:['210000','211000']},{source:'Wallex'});assert.equal(udf.length,2);assert.equal(udf[1].close,211000);
const day=Date.UTC(2026,7,31),rows=[];for(let h=16;h<=20;h++)rows.push({ts:day+h*3600000,close:210000+h,source:'x'});const anchors=hourlyToLockAnchors(rows);assert.equal(anchors.length,1);assert.equal(new Date(anchors[0].anchorAt).getUTCHours(),20);assert.equal(anchors[0].close,210019);
const depth=parseWallexDepth({result:{bid:[{price:'210000',quantity:20},{price:'209900',quantity:10}],ask:[{price:'210200',quantity:5}]}},210100);assert.ok(depth.imbalance>0);
assert.ok(parseWallexTrades({result:{latestTrades:[{quantity:'10',isBuyOrder:true},{quantity:'2',isBuyOrder:false}]}}).tradeImbalance>0);
assert.ok(parseNobitexTrades({trades:[{volume:'3',type:'buy'},{volume:'1',type:'sell'}]}).tradeImbalance>0);

const now=new Date('2026-09-01T20:00:00Z'),snaps=[];for(let i=0;i<16;i++){const at=new Date(now.getTime()-(15-i)*30*60000).toISOString(),usd=200000*(1+i*.0004),usdt=201000*(1+i*.0007);snaps.push({at,usd,usdt,news:i/30,macro:0,health:{currentMarket:true,usdt:true,news:true,macro:true}})}const intra=deriveIntradayFeatures(snaps,now);assert.ok(intra.coverage>.9);assert.ok(intra.usdtChange6h>intra.usdChange6h);

const history=[],historicalUSDT=[];let p=150000,u=150800;for(let i=0;i<230;i++){const d=new Date(Date.UTC(2025,0,1+i)).toISOString().slice(0,10),shock=.002*Math.sin(i/8),ulead=.0018*Math.sin((i+1)/8);u*=Math.exp(.0008+ulead);p*=Math.exp(.0007+shock+.22*ulead);history.push({date:d,close:p});historicalUSDT.push({date:d,close:u,sourceCount:2,disagreementPct:.002})}const f=buildForecast({history,historicalUSDT,currentMarket:{mid:p,asOf:history.at(-1).date,disagreementPct:.003,quality:'high'},usdt:{mid:u,exchangeCount:2,disagreementPct:.003,spreadPct:.001},news:{score:0,relevantCount:0},macro:{score:0},intraday:intra,now:new Date('2026-08-18T20:00:00Z')});assert.ok(Number.isFinite(f.forecast));assert.ok(f.model.historicalUSDTSamples>=200);assert.ok(Object.keys(f.model.weights).length>=9);

const template=metaFeatureVector(f),errors=[];for(let i=0;i<48;i++){const x=[...template];x[0]=(i-24)/2000;x[6]=Math.sin(i/5)*.3;const logError=.35*x[0]+.004*x[6];errors.push({logError,metaFeatures:x})}const meta=metaAdjustment({errors},f);assert.ok(Number.isFinite(meta.adjustment));const shadowRows=[];for(let i=0;i<40;i++)shadowRows.push({errors:{fullRaw:1.0,noNews:1.3,noUSDT:.75,noMacro:1.02,noIntraday:1.01,noAED:1.0,noGoldFX:1.0,coreOnly:1.08}});const policy=deriveSignalScales({rows:shadowRows});assert.ok(policy.scales.news>policy.scales.usdt);assert.ok(policy.scales.usdt<.9);const scaled=buildForecast({history,historicalUSDT,currentMarket:{mid:p,asOf:history.at(-1).date,disagreementPct:.003,quality:'high'},usdt:{mid:u,exchangeCount:2,disagreementPct:.003,spreadPct:.001},news:{score:.6,relevantCount:4},macro:{score:.4,components:{}},intraday:intra,signalScales:policy.scales,now:new Date('2026-08-18T20:00:00Z')});assert.ok(Number.isFinite(scaled.forecast));console.log('production-features ok',Object.keys(f.model.weights).length,meta.mode,policy.scales);
