import {clamp,mean,median,std,quantile,mad,ema,returns,rsi,ridgePredict,nextTehranDate,weightedMean,weightedQuantile} from './utils.mjs';

function theilSenNext(v){const y=v.map(Math.log),n=y.length;if(n<5)return v.at(-1);const slopes=[];for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)slopes.push((y[j]-y[i])/(j-i));const s=median(slopes),ints=y.map((q,i)=>q-s*i),c=median(ints);return Math.exp(c+s*n)}
function holt(v){if(v.length<6)return v.at(-1);let l=v[0],t=v[1]-v[0];const a=.34,b=.13;for(let i=1;i<v.length;i++){const prev=l;l=a*v[i]+(1-a)*(l+t);t=b*(l-prev)+(1-b)*t}return Math.max(1,l+.62*t)}
function ar3(v){const r=returns(v);if(r.length<24)return v.at(-1);const X=[],y=[];for(let i=3;i<r.length;i++){X.push([r[i-1],r[i-2],r[i-3]]);y.push(r[i])}const p=ridgePredict(X,y,[r.at(-1),r.at(-2),r.at(-3)],5);return v.at(-1)*Math.exp(clamp(p,-.06,.06))}
function feature(v){const r=returns(v),last=v.at(-1),m20=mean(v.slice(-20)),s20=std(v.slice(-20))||last*.01;const rr=k=>r.at(-k)||0,mom=k=>v.length>k?Math.log(last/v.at(-k-1)):0,vol=k=>std(r.slice(-k));return [rr(1),rr(2),rr(3),mom(3),mom(5),mom(10),mom(20),vol(5),vol(10),vol(20),ema(v.slice(-30),3)/ema(v.slice(-40),10)-1,ema(v.slice(-60),5)/ema(v.slice(-60),20)-1,(rsi(v,14)-50)/50,(last-m20)/s20,Math.log(last/Math.max(...v.slice(-20)))]}
function ridgeNext(v){if(v.length<45)return v.at(-1);const X=[],y=[];for(let t=25;t<v.length-1;t++){X.push(feature(v.slice(0,t+1)));y.push(Math.log(v[t+1]/v[t]))}const p=ridgePredict(X,y,feature(v),4);return v.at(-1)*Math.exp(clamp(p,-.055,.055))}
function knnNext(v){if(v.length<55)return v.at(-1);const X=[],y=[];for(let t=30;t<v.length-1;t++){X.push(feature(v.slice(0,t+1)));y.push(Math.log(v[t+1]/v[t]))}const x=feature(v),p=x.length,mu=Array(p).fill(0),sd=Array(p).fill(1);for(let j=0;j<p;j++){const c=X.map(r=>r[j]);mu[j]=mean(c);sd[j]=std(c)||1}const z=r=>r.map((q,j)=>(q-mu[j])/sd[j]),zx=z(x);const d=X.map((r,i)=>({i,d:Math.sqrt(mean(z(r).map((q,j)=>(q-zx[j])**2)))})).sort((a,b)=>a.d-b.d).slice(0,Math.min(14,Math.max(6,Math.round(Math.sqrt(X.length)))));const pred=weightedMean(d.map(o=>y[o.i]),d.map(o=>1/(o.d+.25)));return v.at(-1)*Math.exp(clamp(pred,-.05,.05))}

function usdtMap(rows){return new Map((rows||[]).filter(x=>x?.date&&Number.isFinite(x.close)&&x.close>1000).map(x=>[x.date,x.close]))}
function crossFeature(v,dates,uMap){if(!uMap?.size||dates.length!==v.length)return null;const pairs=[];for(let i=Math.max(0,v.length-30);i<v.length;i++){const u=uMap.get(dates[i]);if(Number.isFinite(u)&&u>1000)pairs.push({i,u,usd:v[i],p:Math.log(u/v[i])})}if(pairs.length<6)return null;const a=pairs.at(-1),b=pairs.at(-2),c=pairs.at(-4)??pairs[0],prem=pairs.map(x=>x.p),pm=mean(prem),ps=std(prem)||.004;const u1=Math.log(a.u/b.u),u3=Math.log(a.u/c.u),d1=Math.log(a.usd/b.usd),d3=Math.log(a.usd/c.usd);return [(a.p-pm)/ps,a.p,u1,u3,u1-d1,u3-d3,std(prem.slice(-7)),pairs.length/30]}
function crossRidgeNext(v,dates,uMap){if(v.length<70||!uMap?.size)return null;const X=[],y=[];for(let t=35;t<v.length-1;t++){const vv=v.slice(0,t+1),dd=dates.slice(0,t+1),cf=crossFeature(vv,dd,uMap);if(!cf)continue;X.push([...feature(vv),...cf]);y.push(Math.log(v[t+1]/v[t]))}const cf=crossFeature(v,dates,uMap);if(X.length<32||!cf)return null;const p=ridgePredict(X,y,[...feature(v),...cf],7);return v.at(-1)*Math.exp(clamp(p,-.055,.055))}

function modelSet(v,dates,historicalUSDT){const last=v.at(-1),r=returns(v),recent=r.slice(-6),vol=std(r.slice(-14)),m20=mean(v.slice(-20)),s20=std(v.slice(-20))||1,z=(last-m20)/s20;const drift=.42*(recent.at(-1)||0)+.28*median(recent)+.30*mean(r.slice(-10));const momentum=median([mean(r.slice(-3)),mean(r.slice(-5)),mean(r.slice(-10))]);const out={naive:last,ewma:last*Math.exp(clamp(drift,-.05,.05)),holt:holt(v.slice(-30)),theilsen:theilSenNext(v.slice(-18)),momentum:last*Math.exp(clamp(momentum,-.05,.05)),ar3:ar3(v.slice(-90)),revert:last*Math.exp(clamp(-.12*z*Math.max(vol,.002),-.022,.022)),ridge:ridgeNext(v),analog:knnNext(v)};const cr=crossRidgeNext(v,dates,usdtMap(historicalUSDT));if(Number.isFinite(cr))out.crossRidge=cr;return out}
function cappedNormalize(raw,cap=.26){let w={...raw};for(let k=0;k<7;k++){let s=Object.values(w).reduce((a,b)=>a+b,0)||1;for(const n in w)w[n]/=s;let excess=0,free=[];for(const n in w){if(w[n]>cap){excess+=w[n]-cap;w[n]=cap}else free.push(n)}if(excess<1e-9||!free.length)break;const fs=free.reduce((a,n)=>a+w[n],0)||1;for(const n of free)w[n]+=excess*w[n]/fs}const s=Object.values(w).reduce((a,b)=>a+b,0)||1;for(const n in w)w[n]/=s;return w}
function scoreRows(rows,names){const stats={};for(const n of names){let ape=0,ae=0,sw=0,dir=0;const residual=[];let samples=0;for(const q of rows){const p=q.m?.[n];if(!Number.isFinite(p))continue;const e=Math.abs(p-q.actual),a=e/q.actual;ape+=a*q.w;ae+=e*q.w;sw+=q.w;dir+=(Math.sign(p-q.last)===Math.sign(q.actual-q.last)?1:0)*q.w;residual.push(Math.log(q.actual/p));samples++}if(samples>=5)stats[n]={mape:ape/(sw||1),mae:ae/(sw||1),direction:dir/(sw||1),residual,samples}}return stats}
function weightsFromStats(stats){const naive=stats.naive?.mape||.03,raw={};for(const [n,s] of Object.entries(stats)){if(s.samples<5)continue;const skill=clamp(naive/(s.mape+.0007),.30,2.2),directionFactor=.72+.56*s.direction;raw[n]=Math.pow(skill,1.5)*directionFactor/Math.pow(s.mape+.0035,1.08)}if(!Object.keys(raw).length)return {naive:1};return cappedNormalize(raw,.26)}
function mixWeights(a,b,p=.55){const raw={};for(const n of new Set([...Object.keys(a||{}),...Object.keys(b||{})]))raw[n]=(a?.[n]||0)*(1-p)+(b?.[n]||0)*p;return cappedNormalize(raw,.26)}
function robustBlend(models,weights,last){const rows=Object.entries(models||{}).filter(([n,p])=>Number.isFinite(p)&&p>0&&(weights?.[n]||0)>0).map(([n,p])=>({n,r:Math.log(p/last),w:weights[n]}));if(!rows.length)return last;const center=median(rows.map(x=>x.r)),scale=Math.max(.0015,1.4826*mad(rows.map(x=>x.r)));const rw=rows.map(x=>x.w/(1+(Math.abs(x.r-center)/(2.75*scale))**2));const r=weightedMean(rows.map(x=>x.r),rw);return last*Math.exp(r)}
function weightsForRows(rows,names,regime){const globalStats=scoreRows(rows,names),globalWeights=weightsFromStats(globalStats),same=rows.filter(x=>x.regime===regime);if(same.length<12)return {weights:globalWeights,globalStats,regimeSamples:same.length};const regimeStats=scoreRows(same,names),regimeWeights=weightsFromStats(regimeStats);return {weights:mixWeights(globalWeights,regimeWeights,.58),globalStats,regimeStats,regimeSamples:same.length}}
function tech(v){const r=returns(v),last=v.at(-1),m20=mean(v.slice(-20)),s20=std(v.slice(-20))||1,vol=std(r.slice(-14));const mom10=v.length>10?Math.log(last/v.at(-11)):0;return {volatility:vol,rsi14:rsi(v,14),emaSpread:ema(v.slice(-60),5)/ema(v.slice(-60),20)-1,momentum3:v.length>3?Math.log(last/v.at(-4)):0,momentum10:mom10,z20:(last-m20)/s20,regime:Math.abs(r.at(-1)||0)>2.5*Math.max(vol,.001)?'shock':Math.abs(mom10)>1.2*Math.max(vol,.001)?'trend':'range'}}
function compareEnsembleWindow(rows){if(!rows?.length)return {samples:0,ensembleMape:null,naiveMape:null,skill:null};let e=0,n=0;for(const q of rows){e+=Math.abs(q.p/q.actual-1);n+=Math.abs(q.last/q.actual-1)}e/=rows.length;n/=rows.length;return {samples:rows.length,ensembleMape:e,naiveMape:n,skill:n/(e+.0001)}}
function nestedBacktest(v,dates,historicalUSDT){const rows=[],start=Math.max(55,v.length-180),names=new Set(['naive']);for(let t=start;t<v.length-1;t++){const h=v.slice(0,t+1),d=dates.slice(0,t+1),m=modelSet(h,d,historicalUSDT),actual=v[t+1],last=v[t],age=v.length-2-t,w=Math.exp(-age/60),regime=tech(h).regime;Object.keys(m).forEach(n=>names.add(n));rows.push({actual,last,m,w,t,regime})}const nameList=[...names],currentRegime=tech(v).regime,final=weightsForRows(rows,nameList,currentRegime),ensembleRows=[];for(let i=14;i<rows.length;i++){const prior=rows.slice(0,i),q=rows[i],wf=weightsForRows(prior,nameList,q.regime),p=robustBlend(q.m,wf.weights,q.last);ensembleRows.push({...q,p})}let ape=0,ae=0,sw=0,dir=0;for(const q of ensembleRows){const e=Math.abs(q.p-q.actual),a=e/q.actual;ape+=a*q.w;ae+=e*q.w;sw+=q.w;dir+=(Math.sign(q.p-q.last)===Math.sign(q.actual-q.last)?1:0)*q.w}const ens={mape:ape/(sw||1),mae:ae/(sw||1),direction:dir/(sw||1),samples:ensembleRows.length};return {weights:final.weights,stats:final.globalStats,regimeStats:final.regimeStats||null,regimeSamples:final.regimeSamples,ensemble:ens,rows,ensembleRows,currentRegime}}

export function buildForecast({history,aedHistory=null,localGoldHistory=null,historicalUSDT=null,currentMarket=null,usdt=null,news=null,macro=null,intraday=null,now=new Date(),metaAdjustment=0,signalScales=null}){const clean=history.filter(x=>Number.isFinite(x.close)&&x.close>1000&&x.date).sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(-620);if(clean.length<55)throw new Error('Need at least 55 valid USD observations');let v=clean.map(x=>x.close),dates=clean.map(x=>x.date);if(currentMarket?.mid&&Number.isFinite(currentMarket.mid)){const last=v.at(-1),gap=Math.abs(currentMarket.mid/last-1),lastDate=dates.at(-1),liveDate=currentMarket.asOf||lastDate,trusted=currentMarket.quality!=='conflicted'&&(currentMarket.disagreementPct??1)<.025&&currentMarket.hasTGJU&&(currentMarket.aedCrossCheckPct==null||currentMarket.aedCrossCheckPct<.08);if(gap<.12||(trusted&&gap<.35)){if(liveDate>lastDate){v=[...v,currentMarket.mid];dates=[...dates,liveDate]}else if(liveDate===lastDate)v=[...v.slice(0,-1),currentMarket.mid]}else if(trusted&&gap>=.35){throw new Error('Trusted live USD discontinuity exceeds 35% circuit breaker')}}
const last=v.at(-1),m=modelSet(v,dates,historicalUSDT),bt=nestedBacktest(v,dates,historicalUSDT),recent30=compareEnsembleWindow(bt.ensembleRows.slice(-30)),recent60=compareEnsembleWindow(bt.ensembleRows.slice(-60));let base=robustBlend(m,bt.weights,last),t=tech(v),naiveMape=bt.stats.naive?.mape||.03,ensMape=bt.ensemble.mape||naiveMape,baseRet=Math.log(base/last);if(bt.ensemble.samples>=24&&ensMape>naiveMape*1.01)baseRet*=clamp(naiveMape/(ensMape+.0001),.10,.88);if(bt.ensemble.samples>=30&&ensMape>naiveMape*1.12)baseRet=0;
let adj=0;const external={};const ss=n=>clamp(Number.isFinite(signalScales?.[n])?signalScales[n]:1,0,1.25);if(usdt?.mid){const premium=clamp(usdt.mid/last-1,-.07,.07),imb=clamp(usdt.imbalance||0,-1,1),flow=clamp(usdt.tradeImbalance||0,-1,1),mom=clamp(usdt.momentum24h||0,-.08,.08),spread=clamp(usdt.spreadPct||0,0,.03);const trust=clamp(1-(usdt.disagreementPct||0)/.035,0,1)*(1-clamp(spread/.018,0,.8))*clamp((usdt.exchangeCount||1)/2,0.45,1);const rawA=clamp((.22*premium+.055*mom+.0018*imb+.0012*flow)*trust,-.013,.013),scale=ss('usdt'),a=rawA*scale;adj+=a;external.usdt={premium,momentum24h:mom,imbalance:imb,tradeImbalance:flow,trust,rawAdjustment:rawA,scale,adjustment:a}}
if(aedHistory?.length>=4){const aed=aedHistory.filter(x=>Number.isFinite(x.close)&&x.close>0).sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(aed.length>=4){const implied=aed.at(-1).close*3.6725,premium=clamp(implied/last-1,-.05,.05),mom=Math.log(aed.at(-1).close/aed.at(-4).close),usdMom=v.length>=4?Math.log(last/v.at(-4)):0,rawA=clamp(.075*premium+.028*(mom-usdMom),-.0038,.0038),scale=ss('aed'),a=rawA*scale;adj+=a;external.aed={impliedUSD:implied,premium,momentumGap:mom-usdMom,rawAdjustment:rawA,scale,adjustment:a}}}
if(localGoldHistory?.length>=2&&macro?.components?.gold?.ret!=null){const g=localGoldHistory.filter(x=>Number.isFinite(x.close)&&x.close>0).sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(g.length>=2){const localRet=Math.log(g.at(-1).close/g.at(-2).close),globalRet=macro.components.gold.ret||0,fxProxy=clamp(localRet-globalRet,-.06,.06),rawA=clamp(fxProxy*.05,-.0028,.0028),scale=ss('goldFX'),a=rawA*scale;adj+=a;external.goldFX={fxProxy,rawAdjustment:rawA,scale,adjustment:a}}}
if(news&&Number.isFinite(news.score)){const rawA=clamp(news.score*Math.max(t.volatility,.004)*.38,-.0105,.0105),scale=ss('news'),a=rawA*scale;adj+=a;external.news={score:news.score,relevantCount:news.relevantCount,rawAdjustment:rawA,scale,adjustment:a}}
if(macro&&Number.isFinite(macro.score)){const rawA=clamp(macro.score*Math.max(t.volatility,.004)*.105,-.0035,.0035),scale=ss('macro'),a=rawA*scale;adj+=a;external.macro={score:macro.score,rawAdjustment:rawA,scale,adjustment:a}}
if(intraday){const lead=clamp((intraday.usdtChange6h||0)-(intraday.usdChange6h||0),-.05,.05),prem=clamp(intraday.premiumChange6h||0,-.04,.04),phys=clamp(intraday.usdChange6h||0,-.04,.04),newsDelta=clamp(intraday.newsDelta6h||0,-1,1),coverage=clamp(intraday.coverage||0,0,1),rawA=clamp((.085*lead+.05*prem+.018*phys+.0007*newsDelta)*coverage,-.0042,.0042),scale=ss('intraday'),a=rawA*scale;adj+=a;external.intraday={...intraday,lead,rawAdjustment:rawA,scale,adjustment:a}}
const meta=clamp(metaAdjustment||0,-.007,.007);adj+=meta;external.metaAdjustment=meta;if(currentMarket?.disagreementPct>.012)adj*=.72;const raw=baseRet+adj,maxMove=clamp(Math.max(.014,2.55*t.volatility),.014,.06),guard=clamp(raw,-maxMove,maxMove);let forecast=last*Math.exp(guard);const step=forecast>=100000?10:5;forecast=Math.round(forecast/step)*step;
const regimeResidual=bt.ensembleRows.filter(x=>x.regime===t.regime).map(x=>({r:Math.abs(Math.log(x.actual/x.p)),w:x.w})),allResidual=bt.ensembleRows.map(x=>({r:Math.abs(Math.log(x.actual/x.p)),w:x.w})),rr=regimeResidual.length>=12?regimeResidual:allResidual,p80=weightedQuantile(rr.map(x=>x.r),rr.map(x=>x.w),.8),p95=weightedQuantile(rr.map(x=>x.r),rr.map(x=>x.w),.95);const dispersion=std(Object.values(m).filter(Number.isFinite).map(x=>Math.log(x/last))),sourcePenalty=(currentMarket?.disagreementPct||0)*5+(usdt?.disagreementPct||0)*2,skill=clamp(naiveMape/(ensMape+.0001),.45,1.6),historicalUSDTSamples=(historicalUSDT||[]).length,confidence=Math.round(clamp(58+22*(skill-1)-dispersion*430-sourcePenalty*100+(bt.ensemble.samples>=40?8:0)+(bt.regimeSamples>=15?4:0)+(historicalUSDTSamples>=120?3:0),18,95));const quality=bt.ensemble.samples>=28&&confidence>=60&&skill>=.94&&(recent30.skill==null||recent30.skill>=.82)&&(!currentMarket||currentMarket.disagreementPct<.022)?'high':confidence>=45?'medium':'low';return {targetDate:nextTehranDate(now),forecast,current:last,changePct:(forecast/last-1)*100,generatedAt:now.toISOString(),confidence,quality,interval80Pct:p80*100,interval95Pct:p95*100,model:{name:'Adaptive Multi-Signal Ensemble v6',version:'6.0.0',weights:bt.weights,backtest:{ensemble:{mape:ensMape,mae:bt.ensemble.mae,direction:bt.ensemble.direction,samples:bt.ensemble.samples},naive:{mape:naiveMape,mae:bt.stats.naive?.mae,direction:bt.stats.naive?.direction},skillVsNaive:skill,recent30,recent60,regime:t.regime,regimeSamples:bt.regimeSamples},technical:t,external,guardrailPct:maxMove*100,modelDispersionPct:dispersion*100,historicalUSDTSamples,currentMarket,signalScales:{usdt:ss('usdt'),aed:ss('aed'),goldFX:ss('goldFX'),news:ss('news'),macro:ss('macro'),intraday:ss('intraday')}}}}
