import {clamp,stripHtml} from './utils.mjs';
const RULES=[
{id:'sanctions_relief',re:/(sanctions? (relief|eas|waiver|lift)|lift(?:ed|s)? sanctions|waiver.*iran|unfreeze.*iran|release.*frozen|رفع تحریم|کاهش تحریم|تعلیق تحریم|آزادسازی.*دارایی)/i,dir:-1,importance:1.2,halfLife:60},
{id:'sanctions_new',re:/(new sanctions|impos(?:e|es|ed|ing).*sanctions|sanction(?:s|ed).*iran|snapback|maximum pressure|blacklist|designation.*iran|تحریم جدید|اعمال تحریم|مکانیسم ماشه|اسنپ بک|فشار حداکثری)/i,dir:1,importance:1.25,halfLife:60},
{id:'military_deescalation',re:/(ceasefire|de-?escalat|truce|stand down|halt.*attack|end.*hostilit|آتش.?بس|کاهش تنش|توقف حمله|پایان درگیری)/i,dir:-1,importance:1.4,halfLife:24},
{id:'military_escalation',re:/(attack|airstrike|missile|drone attack|war|military escalation|bombard|blockade|close.*strait|حمله|حمله هوایی|موشک|پهپاد|جنگ|تشدید تنش|بمباران|بستن.*تنگه)/i,dir:1,importance:1.5,halfLife:18},
{id:'nuclear_progress',re:/(nuclear (deal|agreement|breakthrough)|talks? (resume|advance|progress)|diplomatic breakthrough|framework agreement|توافق هسته.?ای|پیشرفت مذاکرات|ازسرگیری مذاکرات|توافق اولیه)/i,dir:-.9,importance:1.2,halfLife:48},
{id:'nuclear_breakdown',re:/(talks? (collapse|fail|deadlock|break down)|nuclear deadlock|rejects? deal|شکست مذاکرات|بن.?بست مذاکرات|رد توافق|توقف مذاکرات)/i,dir:.9,importance:1.15,halfLife:48},
{id:'iaea_escalation',re:/(iaea.*(censure|resolution|non.?compliance)|board.*governors.*iran|آژانس.*(قطعنامه|عدم همکاری|محکوم)|شورای حکام.*ایران)/i,dir:.7,importance:1.0,halfLife:48},
{id:'iaea_cooperation',re:/(iaea.*cooperat|inspectors?.*return|آژانس.*همکاری|بازگشت بازرسان|توافق.*آژانس)/i,dir:-.5,importance:.85,halfLife:36},
{id:'cbi_supply_cut',re:/(central bank.*(cut|halt|suspend|restrict).*(currency|forex|dollar).*supply|(cut|halt|suspend|restrict).*foreign exchange supply|(توقف|کاهش|محدودیت).*(عرضه|تامین|تخصیص|فروش).*ارز|کاهش.*تزریق ارز)/i,dir:.82,importance:1.0,halfLife:18},
{id:'cbi_support',re:/(central bank.*(interven|inject|supply)|inject.*(dollar|currency|forex)|foreign exchange supply|currency market intervention|بانک مرکزی.*(مداخله|تزریق|عرضه|تامین|تخصیص|فروش).*ارز|تزریق ارز|عرضه ارز|عرضه دلار|فروش ارز|تامین ارز|تخصیص ارز|بازارساز)/i,dir:-.85,importance:1.0,halfLife:16},
{id:'fx_stress',re:/(currency crisis|rial (falls|slides|plunges|record low)|capital flight|foreign exchange shortage|reserve depletion|بحران ارزی|سقوط ریال|رکورد.*دلار|کمبود ارز|خروج سرمایه|کاهش ذخایر)/i,dir:.8,importance:1.0,halfLife:30},
{id:'oil_export_hit',re:/(iran.*oil.*(sanction|shipment.*blocked|export.*fall|export.*drop)|seize.*iran.*oil|کاهش صادرات نفت|تحریم.*نفت|توقیف.*نفتکش)/i,dir:.65,importance:.9,halfLife:72},
{id:'oil_export_relief',re:/(iran.*oil.*(export.*rise|sales.*rise|waiver)|oil sanctions waiver|افزایش صادرات نفت|افزایش فروش نفت|معافیت نفتی)/i,dir:-.5,importance:.8,halfLife:72},
{id:'domestic_unrest',re:/(mass protest|nationwide protest|general strike|political unrest|state of emergency|اعتراضات سراسری|اعتصاب سراسری|ناآرامی گسترده|وضعیت اضطراری)/i,dir:.6,importance:.8,halfLife:24}
];
const AUTH=[[/ofac\.treasury\.gov|home\.treasury\.gov|state\.gov|whitehouse\.gov|iaea\.org/i,1.5],[/reuters(?:\.com)?|bloomberg(?:\.com)?|apnews(?:\.com)?|financial times|ft\.com|wsj(?:\.com)?/i,1.4],[/bbc\.|aljazeera\.|cnbc\.|economist\.com|nytimes\.com|washingtonpost\.com/i,1.18],[/cbi\.ir/i,1.35],[/irna\.ir|isna\.ir|tasnimnews\.com|mehrnews\.com|president\.ir/i,1.05]];
const authority=d=>{for(const [r,w] of AUTH)if(r.test(d||''))return w;return .82};
const words=s=>new Set(String(s||'').toLowerCase().replace(/[^a-z0-9\u0600-\u06ff ]/g,' ').split(/\s+/).filter(x=>x.length>2));
const sim=(a,b)=>{const A=words(a),B=words(b);let i=0;for(const x of A)if(B.has(x))i++;const u=A.size+B.size-i;return u?i/u:0};
export function dedupeArticles(articles){const sorted=[...articles].filter(a=>a?.title).sort((a,b)=>new Date(b.publishedAt||0)-new Date(a.publishedAt||0));const out=[];for(const a of sorted){const dup=out.find(x=>sim(x.title,a.title)>.72);if(!dup)out.push(a);else if(authority(a.domain)>authority(dup.domain))out[out.indexOf(dup)]=a}return out}
export function scoreNews(articles,now=new Date()){const uniq=dedupeArticles(articles),events=[];for(const a of uniq){const d=new Date(a.publishedAt||'');if(!Number.isFinite(d.getTime()))continue;const ageHours=(now-d)/3600000;if(ageHours<-.5||ageHours>240)continue;const text=stripHtml(`${a.title||''} ${a.description||''}`);for(const rule of RULES){if(!rule.re.test(text))continue;const fresh=Math.pow(.5,Math.max(0,ageHours)/rule.halfLife),w=rule.importance*authority(a.domain)*fresh;events.push({id:rule.id,title:a.title,domain:a.domain,publishedAt:a.publishedAt,direction:rule.dir,weight:w,contribution:rule.dir*w,url:a.url});break}}const by={};for(const e of events)(by[e.id]??=[]).push(e);let total=0,weight=0;for(const arr of Object.values(by)){arr.sort((a,b)=>b.weight-a.weight);const domainSeen={};arr.forEach((e,i)=>{const domain=String(e.domain||'unknown').toLowerCase(),n=domainSeen[domain]||0;domainSeen[domain]=n+1;const familySat=1/Math.sqrt(i+1),domainSat=1/Math.sqrt(n+1),sat=familySat*domainSat;total+=e.contribution*sat;weight+=e.weight*sat})}const raw=weight?total/weight:0,score=Math.tanh(raw*1.35);const domains=new Set(events.map(e=>String(e.domain||'').toLowerCase()).filter(Boolean));return {score:clamp(score,-1,1),count:articles.length,uniqueCount:uniq.length,relevantCount:events.length,independentDomains:domains.size,topEvents:[...events].sort((a,b)=>Math.abs(b.contribution)-Math.abs(a.contribution)).slice(0,12)}}
