import {safeNum,normalizeDigits,stripHtml,median,mean,clamp,tehranDate} from './utils.mjs';
import {scoreNews} from './news-engine.mjs';
const UA='Mozilla/5.0 (compatible; TMRW-USD/6.0; +https://netlify.app)';
export const timeoutFetch=async(url,options={},ms=7500)=>{const c=new AbortController(),id=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...options,signal:c.signal,headers:{'user-agent':UA,accept:'*/*',...(options.headers||{})}})}finally{clearTimeout(id)}};

function validOHLC(open,low,high,close){
  if(![open,low,high,close].every(x=>Number.isFinite(x)&&x>0))return false;
  const eps=Math.max(1,high*.000001);
  return high+eps>=low&&open>=low-eps&&open<=high+eps&&close>=low-eps&&close<=high+eps&&high/low<2.5;
}
export function validateHistorySeries(rows,{minRows=55,maxLagDays=12,now=new Date()}={}){
  const clean=[...new Map((rows||[]).filter(x=>x?.date&&Number.isFinite(x.close)&&x.close>0).map(x=>[x.date,x])).values()].sort((a,b)=>a.date.localeCompare(b.date));
  if(clean.length<minRows)return {ok:false,reason:'too-short',rows:clean.length};
  let maxJump=0;
  for(let i=1;i<clean.length;i++){const a=clean[i-1].close,b=clean[i].close;if(a>0&&b>0)maxJump=Math.max(maxJump,Math.abs(b/a-1));}
  if(maxJump>.65)return {ok:false,reason:'implausible-unit-jump',rows:clean.length,maxJump};
  const last=clean.at(-1)?.date,lag=last?(new Date(`${tehranDate(now)}T00:00:00Z`)-new Date(`${last}T00:00:00Z`))/86400000:Infinity;
  if(Number.isFinite(lag)&&lag>maxLagDays)return {ok:false,reason:'stale',rows:clean.length,lastDate:last,lagDays:lag,maxJump};
  return {ok:true,rows:clean.length,lastDate:last,lagDays:lag,maxJump};
}

export function parseTGJUHistoryHtml(html,source='TGJU'){const rows=String(html).split(/<\/tr>/i),out=[];for(const row of rows){const cells=[...row.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(m=>normalizeDigits(stripHtml(m[1])));if(cells.length>=7){const dateCell=cells.find(x=>/^20\d{2}[\/-]\d{2}[\/-]\d{2}$/.test(x));const vals=cells.slice(0,4).map(safeNum);if(dateCell&&vals.every(Number.isFinite)){const [o,l,h,c]=vals.map(x=>x/10);if(validOHLC(o,l,h,c))out.push({date:dateCell.replaceAll('/','-'),open:o,low:l,high:h,close:c,source});continue}}const text=normalizeDigits(stripHtml(row)),dm=text.match(/20\d{2}[\/-]\d{2}[\/-]\d{2}/);if(!dm)continue;const nums=[...text.slice(0,dm.index).matchAll(/\d{1,3}(?:,\d{3})+(?:\.\d+)?/g)].map(m=>safeNum(m[0]));if(nums.length<4)continue;const [open,low,high,close]=nums.slice(0,4);if([open,low,high,close].every(Number.isFinite)){const [o,l,h,c]=[open,low,high,close].map(x=>x/10);if(validOHLC(o,l,h,c))out.push({date:dm[0].replaceAll('/','-'),open:o,low:l,high:h,close:c,source})}}return [...new Map(out.map(x=>[x.date,x])).values()].sort((a,b)=>a.date.localeCompare(b.date))}
export function parseTGJUChartData(text,source='TGJU'){const out=[];const normalized=normalizeDigits(String(text));for(const m of normalized.matchAll(/(?:date|d)["']?\s*[:=]\s*["']?(20\d{2}[\/-]\d{2}[\/-]\d{2})["']?[\s\S]{0,260}?(?:open|o)["']?\s*[:=]\s*["']?([0-9,\.]+)["']?[\s\S]{0,160}?(?:low|l)["']?\s*[:=]\s*["']?([0-9,\.]+)["']?[\s\S]{0,160}?(?:high|h)["']?\s*[:=]\s*["']?([0-9,\.]+)["']?[\s\S]{0,160}?(?:close|c)["']?\s*[:=]\s*["']?([0-9,\.]+)/gi)){const vals=m.slice(2,6).map(safeNum);if(vals.every(Number.isFinite)){const [o,l,h,c]=vals.map(x=>x/10);if(validOHLC(o,l,h,c))out.push({date:m[1].replaceAll('/','-'),open:o,low:l,high:h,close:c,source})}}return [...new Map(out.map(x=>[x.date,x])).values()].sort((a,b)=>a.date.localeCompare(b.date))}
export function parseTGJUSummaryJson(payload,source='TGJU summary'){const rows=Array.isArray(payload?.data)?payload.data:[],out=[];for(const row of rows){const cells=(Array.isArray(row)?row:Object.values(row||{})).map(x=>normalizeDigits(stripHtml(String(x??''))));if(cells.length<7)continue;const dateCell=cells.find(x=>/^20\d{2}[\/-]\d{2}[\/-]\d{2}$/.test(x));const vals=cells.slice(0,4).map(safeNum);if(!dateCell||!vals.every(Number.isFinite))continue;{const [o,l,h,c]=vals.map(x=>x/10);if(validOHLC(o,l,h,c))out.push({date:dateCell.replaceAll('/','-'),open:o,low:l,high:h,close:c,source})}}return [...new Map(out.map(x=>[x.date,x])).values()].sort((a,b)=>a.date.localeCompare(b.date))}
function tgjuSummaryParams(length=5000){const p=new URLSearchParams([['lang','fa'],['order_dir','asc'],['draw','2']]);for(let i=0;i<8;i++){p.append(`columns[${i}][data]`,String(i));p.append(`columns[${i}][name]`,'');p.append(`columns[${i}][searchable]`,'true');p.append(`columns[${i}][orderable]`,'true');p.append(`columns[${i}][search][value]`,'');p.append(`columns[${i}][search][regex]`,'false')}for(const [k,v] of [['start','0'],['length',String(length)],['search',''],['order_col',''],['order_dir',''],['from',''],['to',''],['convert_to_ad','1'],['_',String(Date.now())]])p.append(k,v);return p}
export async function fetchTGJUSummaryHistory(profile='price_dollar_rl',length=5000){
  const hosts=['https://api.tgju.org','https://api.accessban.com'];
  let lastErr;
  for(const host of hosts){
    try{
      const url=`${host}/v1/market/indicator/summary-table-data/${profile}?${tgjuSummaryParams(length)}`;
      const r=await timeoutFetch(url,{headers:{accept:'application/json, text/javascript, */*; q=0.01',origin:'https://www.tgju.org',referer:'https://www.tgju.org/'}},10000);
      if(!r.ok)throw new Error(`TGJU summary ${r.status}`);
      const data=parseTGJUSummaryJson(await r.json(),`${host.includes('accessban')?'Accessban TGJU mirror':'TGJU summary'}:${profile}`);
      const q=validateHistorySeries(data,{minRows:55,maxLagDays:12});
      if(!q.ok)throw new Error(`TGJU summary invalid: ${q.reason}`);
      return data;
    }catch(e){lastErr=e}
  }
  throw lastErr||new Error('TGJU summary unavailable');
}
export function parseUsdMirrorCsv(text,source='TGJU-derived bootstrap mirror'){const lines=normalizeDigits(String(text)).trim().split(/\r?\n/),out=[];if(lines.length<2)return out;const header=lines[0].split(',').map(x=>x.trim().toLowerCase()),idx=n=>header.findIndex(x=>x===n),io=idx('open price'),il=idx('low price'),ih=idx('high price'),ic=idx('close price'),id=idx('gregorian date');if(Math.min(io,il,ih,ic,id)<0)return out;for(const line of lines.slice(1)){const c=line.split(',').map(x=>x.trim());const vals=[io,il,ih,ic].map(i=>safeNum(c[i])),date=(c[id]||'').replaceAll('/','-');if(!/^20\d{2}-\d{2}-\d{2}$/.test(date)||!vals.every(Number.isFinite))continue;{const [o,l,h,c]=vals.map(x=>x/10);if(validOHLC(o,l,h,c))out.push({date,open:o,low:l,high:h,close:c,source})}}return [...new Map(out.map(x=>[x.date,x])).values()].sort((a,b)=>a.date.localeCompare(b.date))}
async function fetchUsdBootstrapMirror(){const r=await timeoutFetch('https://raw.githubusercontent.com/kooroshkz/Dollar-Rial-Toman-Live-Price-Dataset/main/data/Dollar_Rial_Price_Dataset.csv',{},8500);if(!r.ok)throw new Error(`USD bootstrap mirror ${r.status}`);const data=parseUsdMirrorCsv(await r.text());const q=validateHistorySeries(data,{minRows:120,maxLagDays:45});if(!q.ok)throw new Error(`USD bootstrap mirror invalid: ${q.reason}`);return data}
function mergeHistory(primary,secondary){const by=new Map((secondary||[]).map(x=>[x.date,x]));for(const x of primary||[])by.set(x.date,x);return [...by.values()].sort((a,b)=>a.date.localeCompare(b.date))}
export async function fetchTGJUHistory(profile='price_dollar_rl'){let err;try{return await fetchTGJUSummaryHistory(profile,5000)}catch(e){err=e}const urls=[`https://english.tgju.org/profile/${profile}/history`,`https://www.tgju.org/profile/${profile}/history`,`https://www.tgju.org/profile/${profile}/charts-data/history`];let short=[];for(const u of urls){try{const r=await timeoutFetch(u,{},8500);if(!r.ok)throw new Error(`TGJU ${r.status}`);const text=await r.text(),a=parseTGJUHistoryHtml(text,`TGJU:${profile}`),b=parseTGJUChartData(text,`TGJU:${profile}`),data=(b.length>a.length?b:a);if(data.length>short.length)short=data;if(data.length>=55){const q=validateHistorySeries(data,{minRows:55,maxLagDays:12});if(q.ok)return data}}catch(e){err=e}}if(profile==='price_dollar_rl'){try{const mirror=await fetchUsdBootstrapMirror();if(short.length){const overlap=short.filter(x=>mirror.some(y=>y.date===x.date));if(overlap.length>=5){const m=new Map(mirror.map(x=>[x.date,x.close])),ape=overlap.map(x=>Math.abs(x.close/(m.get(x.date)||x.close)-1)),avg=mean(ape);if(avg>.015)throw new Error(`Bootstrap mirror overlap mismatch ${avg}`)}return mergeHistory(short,mirror)}return mirror}catch(e){err=e}}if(short.length>=18)return short;throw err||new Error('TGJU history unavailable')}
export async function fetchTGJULast(profile='price_dollar_rl'){let err;try{const h=await fetchTGJUSummaryHistory(profile,90),x=h.at(-1);if(x?.close)return {value:x.close,source:`TGJU summary:${profile}`,asOf:x.date}}catch(e){err=e}try{const r=await timeoutFetch(`https://english.tgju.org/profile/${profile}`,{},7500);if(!r.ok)throw new Error(`TGJU last ${r.status}`);const text=normalizeDigits(stripHtml(await r.text()));const candidates=[...(text.matchAll(/(?:Last|نرخ فعلی|قیمت فعلی)\s*:?\s*([0-9][0-9,]{3,})/gi))].map(x=>safeNum(x[1])).filter(x=>x>10000);const rial=candidates[0];if(!rial)throw new Error('TGJU last parse failed');let asOf=tehranDate();const dm=text.match(/(20\d{2}[\/-]\d{2}[\/-]\d{2})/);if(dm)asOf=dm[1].replaceAll('/','-');return {value:rial/10,source:`TGJU:${profile}`,asOf}}catch(e){throw err||e}}

export function parseBonbastTelegram(html,now=new Date()){const blocks=String(html).split(/tgme_widget_message_wrap/),rows=[];for(const block of blocks){const dt=block.match(/datetime=["']([^"']+)/i)?.[1],text=normalizeDigits(stripHtml(block));if(!dt||!text)continue;const usd=safeNum(text.match(/دلار\s*[:：]?\s*([0-9,]+)/)?.[1]),usdt=safeNum(text.match(/تتر\s*[:：]?\s*([0-9,]+)/)?.[1]);if(Number.isFinite(usd)||Number.isFinite(usdt))rows.push({usd:Number.isFinite(usd)?usd:null,usdt:Number.isFinite(usdt)?usdt:null,publishedAt:new Date(dt).toISOString(),ageHours:(now-new Date(dt))/3600000,source:'Bonbast Telegram'})}return rows.sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt))[0]||null}
export async function fetchBonbastTelegram(){const r=await timeoutFetch('https://t.me/s/Bonbast_EX',{},7500);if(!r.ok)throw new Error(`Bonbast Telegram ${r.status}`);const row=parseBonbastTelegram(await r.text());if(!row)throw new Error('Bonbast parse failed');return row}
export async function fetchCurrentMarket(){const rs=await Promise.allSettled([fetchTGJULast('price_dollar_rl'),fetchTGJULast('price_aed'),fetchBonbastTelegram()]);const usd=rs[0].status==='fulfilled'?rs[0].value:null,aed=rs[1].status==='fulfilled'?rs[1].value:null,bb=rs[2].status==='fulfilled'?rs[2].value:null,direct=[];if(usd?.value)direct.push({value:usd.value,source:'TGJU USD',asOf:usd.asOf,kind:'direct'});if(bb?.usd&&bb.ageHours<=6)direct.push({value:bb.usd,source:'Bonbast',asOf:tehranDate(new Date(bb.publishedAt)),kind:'direct'});if(!direct.length)return null;const latest=direct.map(x=>x.asOf).sort().at(-1),fresh=direct.filter(x=>x.asOf===latest),vals=fresh.map(x=>x.value),mid=median(vals),spread=vals.length>1?Math.max(...vals)-Math.min(...vals):0,disagreementPct=spread/(mid||1),crossChecks=[];if(aed?.value)crossChecks.push({value:aed.value*3.6725,source:'TGJU AED implied',asOf:aed.asOf,kind:'cross-check'});const aedGap=crossChecks.length?Math.abs(crossChecks[0].value/mid-1):null;const quality=fresh.length>=2&&disagreementPct<.018?'high':fresh.length>=1&&disagreementPct<.03&&(aedGap==null||aedGap<.05)?'medium':'conflicted';return {mid,asOf:latest,points:direct,crossChecks,freshPoints:fresh.length,disagreementPct,aedCrossCheckPct:aedGap,sourceCount:direct.length,hasTGJU:fresh.some(x=>x.source==='TGJU USD'),quality}}

function findMarket(obj){if(!obj||typeof obj!=='object')return null;if(String(obj.symbol||obj.baseSymbol||'').toUpperCase()==='USDTTMN')return obj;if(obj.USDTTMN&&typeof obj.USDTTMN==='object')return obj.USDTTMN;for(const v of Object.values(obj)){const x=findMarket(v);if(x)return x}return null}
export function parseWallexMarkets(j){const m=findMarket(j);if(!m)return null;const s=m.stats||m,bid=safeNum(s.bidPrice??s.bid??s.bestBid),ask=safeNum(s.askPrice??s.ask??s.bestAsk),last=safeNum(s.lastPrice??s.last??s.last_trade_price),mid=bid&&ask?(bid+ask)/2:last;if(!Number.isFinite(mid)||mid<1000)return null;let ch=safeNum(s['24h_ch']??s.change24h??s.percentChange??s.change);if(Number.isFinite(ch)&&Math.abs(ch)>1)ch/=100;return {mid,bid,ask,last,momentum24h:Number.isFinite(ch)?ch:0,spreadPct:bid&&ask?(ask-bid)/mid:0,source:'Wallex'}}
export function parseWallexDepth(j,mid){const r=j?.result||j?.data||j,ask=r?.ask||r?.asks||[],bid=r?.bid||r?.bids||[];if(!Array.isArray(ask)||!Array.isArray(bid))return null;const qty=(side,isBid)=>side.slice(0,30).reduce((sum,x)=>{const p=safeNum(x?.price??x?.[0]),q=safeNum(x?.quantity??x?.amount??x?.[1]);if(!Number.isFinite(p)||!Number.isFinite(q)||q<=0)return sum;if(Number.isFinite(mid)&&mid>0&&Math.abs(p/mid-1)>.02)return sum;return sum+q},0),bv=qty(bid,true),av=qty(ask,false);return {imbalance:(bv-av)/(bv+av||1),bidDepth:bv,askDepth:av}}
export function parseWallexTrades(j){const a=j?.result?.latestTrades||j?.latestTrades||j?.data?.latestTrades||[];let buy=0,sell=0;for(const x of a.slice(0,80)){const q=safeNum(x?.quantity??x?.amount)||0;if(x?.isBuyOrder===true||String(x?.side||'').toUpperCase()==='BUY')buy+=q;else sell+=q}return {tradeImbalance:(buy-sell)/(buy+sell||1),tradeCount:a.length}}
export async function fetchWallexUSDT(){const rs=await Promise.allSettled([timeoutFetch('https://api.wallex.ir/v1/markets',{},6500).then(async r=>{if(!r.ok)throw new Error(`Wallex markets ${r.status}`);const o=parseWallexMarkets(await r.json());if(!o)throw new Error('Wallex USDTTMN parse failed');return o}),timeoutFetch('https://api.wallex.ir/v1/depth?symbol=USDTTMN',{},6500).then(async r=>{if(!r.ok)throw new Error(`Wallex depth ${r.status}`);return r.json()}),timeoutFetch('https://api.wallex.ir/v1/trades?symbol=USDTTMN',{},6500).then(async r=>{if(!r.ok)throw new Error(`Wallex trades ${r.status}`);return r.json()})]);if(rs[0].status!=='fulfilled')throw rs[0].reason;const base=rs[0].value,depth=rs[1].status==='fulfilled'?parseWallexDepth(rs[1].value,base.mid):null,trades=rs[2].status==='fulfilled'?parseWallexTrades(rs[2].value):null;return {...base,imbalance:depth?.imbalance??0,tradeImbalance:trades?.tradeImbalance??0,depthAvailable:!!depth,tradesAvailable:!!trades}}
export function parseNobitexOrderbook(j){const b=j?.bids||j?.data?.bids||[],a=j?.asks||j?.data?.asks||[],bid=safeNum(b?.[0]?.[0]??b?.[0]?.price),ask=safeNum(a?.[0]?.[0]??a?.[0]?.price),last=safeNum(j?.lastTradePrice??j?.data?.lastTradePrice??j?.lastPrice),mid=bid&&ask?(bid+ask)/2:last;if(!Number.isFinite(mid)||mid<1000)return null;const depth=(side,n=20)=>side.slice(0,n).reduce((s,x)=>s+(safeNum(x?.[1]??x?.amount)||0),0),bv=depth(b),av=depth(a);return {mid:mid/10,bid:bid?bid/10:bid,ask:ask?ask/10:ask,last:last?last/10:last,imbalance:(bv-av)/(bv+av||1),momentum24h:0,spreadPct:bid&&ask?(ask-bid)/mid:0,source:'Nobitex',lastUpdate:j?.lastUpdate??j?.data?.lastUpdate??null}}
export function parseNobitexTrades(j){const a=j?.trades||j?.data?.trades||[];let buy=0,sell=0;for(const x of a.slice(0,80)){const q=safeNum(x?.volume??x?.amount)||0;if(String(x?.type||x?.side||'').toLowerCase()==='buy')buy+=q;else sell+=q}return {tradeImbalance:(buy-sell)/(buy+sell||1),tradeCount:a.length}}
export async function fetchNobitexUSDT(){const rs=await Promise.allSettled([timeoutFetch('https://api.nobitex.ir/v3/orderbook/USDTIRT',{},6500).then(async r=>{if(!r.ok)throw new Error(`Nobitex orderbook ${r.status}`);const o=parseNobitexOrderbook(await r.json());if(!o)throw new Error('Nobitex bad book');return o}),timeoutFetch('https://api.nobitex.ir/v2/trades/USDTIRT',{},6500).then(async r=>{if(!r.ok)throw new Error(`Nobitex trades ${r.status}`);return r.json()})]);if(rs[0].status!=='fulfilled')throw rs[0].reason;const base=rs[0].value,trades=rs[1].status==='fulfilled'?parseNobitexTrades(rs[1].value):null;return {...base,tradeImbalance:trades?.tradeImbalance??0,tradesAvailable:!!trades}}
export function parseCoinbaseUsdtTicker(j){const bid=safeNum(j?.bid),ask=safeNum(j?.ask),last=safeNum(j?.price),peg=bid&&ask?(bid+ask)/2:last;if(!Number.isFinite(peg)||peg<.97||peg>1.03)return null;return {peg,bid,ask,source:'Coinbase Exchange USDT-USD',asOf:j?.time||null}}
export async function fetchGlobalUsdtPeg(){const r=await timeoutFetch('https://api.exchange.coinbase.com/products/USDT-USD/ticker',{headers:{accept:'application/json'}},5500);if(!r.ok)throw new Error(`Coinbase USDT-USD ${r.status}`);const o=parseCoinbaseUsdtTicker(await r.json());if(!o)throw new Error('Global USDT peg out of validation range');return {...o,asOf:o.asOf||new Date().toISOString()}}
export async function fetchUSDTConsensus(){const rs=await Promise.allSettled([fetchWallexUSDT(),fetchNobitexUSDT(),fetchBonbastTelegram(),fetchGlobalUsdtPeg()]),ok=[];if(rs[0].status==='fulfilled')ok.push(rs[0].value);if(rs[1].status==='fulfilled')ok.push(rs[1].value);if(rs[2].status==='fulfilled'&&rs[2].value.usdt&&rs[2].value.ageHours<=6)ok.push({mid:rs[2].value.usdt,imbalance:0,tradeImbalance:0,momentum24h:0,spreadPct:0,source:'Bonbast'});if(!ok.length)return null;const peg=rs[3].status==='fulfilled'?rs[3].value:null,rawMid=median(ok.map(x=>x.mid)),mid=rawMid/(peg?.peg||1),dev=Math.max(...ok.map(x=>Math.abs(x.mid/rawMid-1))),exchanges=ok.filter(x=>x.source==='Wallex'||x.source==='Nobitex');return {mid,rawLocalUsdtMid:rawMid,globalPeg:peg,pegAdjusted:!!peg,imbalance:mean(exchanges.map(x=>x.imbalance||0)),tradeImbalance:mean(exchanges.map(x=>x.tradeImbalance||0)),momentum24h:mean(ok.map(x=>x.momentum24h||0)),spreadPct:mean(exchanges.map(x=>x.spreadPct||0)),sources:ok.map(x=>x.source),exchangeCount:exchanges.length,disagreementPct:dev,quality:exchanges.length>=2&&dev<.025?'high':ok.length>=2&&dev<.04?'medium':'low',raw:ok}}

export function parseUDFHistory(j,{divisor=1,source='UDF'}={}){if(!j||j.s==='no_data'||!Array.isArray(j.t)||!Array.isArray(j.c))return[];const out=[];for(let i=0;i<Math.min(j.t.length,j.c.length);i++){const ts=Number(j.t[i])*1000,close=safeNum(j.c[i])/divisor;if(Number.isFinite(ts)&&Number.isFinite(close)&&close>1000)out.push({ts,close,source})}return out.sort((a,b)=>a.ts-b.ts)}
export function hourlyToLockAnchors(rows){const by=new Map;for(const x of rows||[]){const d=new Date(x.ts);if(!Number.isFinite(d.getTime()))continue;const day=d.toISOString().slice(0,10),h=d.getUTCHours();/* Official lock is 23:30 Tehran = 20:00 UTC. The 19:00-20:00 UTC candle is the last fully-known hourly candle at lock time. Keep a small fallback window for provider gaps, but never use a candle that closes after lock. */if(h>19||h<16)continue;const prev=by.get(day);if(!prev||h>new Date(prev.ts).getUTCHours())by.set(day,x)}return [...by.entries()].map(([date,x])=>({date,close:x.close,source:x.source,anchorAt:new Date(x.ts+3600000).toISOString()})).sort((a,b)=>a.date.localeCompare(b.date))}
async function fetchWallexUSDTHourly(fromSec,toSec){const u=`https://api.wallex.ir/v1/udf/history?symbol=USDTTMN&resolution=60&from=${Math.floor(fromSec)}&to=${Math.floor(toSec)}`,r=await timeoutFetch(u,{},8000);if(!r.ok)throw new Error(`Wallex UDF ${r.status}`);return parseUDFHistory(await r.json(),{divisor:1,source:'Wallex'})}
async function fetchNobitexUSDTHourly(fromSec,toSec){const u=`https://api.nobitex.ir/market/udf/history?symbol=USDTIRT&resolution=60&from=${Math.floor(fromSec)}&to=${Math.floor(toSec)}`,r=await timeoutFetch(u,{},8000);if(!r.ok)throw new Error(`Nobitex UDF ${r.status}`);return parseUDFHistory(await r.json(),{divisor:10,source:'Nobitex'})}
export async function fetchUSDTAnchorWindow({from,to}){const fromSec=Math.floor(new Date(from).getTime()/1000),toSec=Math.floor(new Date(to).getTime()/1000);if(!Number.isFinite(fromSec)||!Number.isFinite(toSec)||toSec<=fromSec)throw new Error('Invalid anchor window');const rs=await Promise.allSettled([fetchWallexUSDTHourly(fromSec,toSec),fetchNobitexUSDTHourly(fromSec,toSec)]),anchors=rs.map(x=>x.status==='fulfilled'?hourlyToLockAnchors(x.value):[]),days=new Set(anchors.flatMap(a=>a.map(x=>x.date))),out=[];for(const date of [...days].sort()){const vals=[];for(const arr of anchors){const x=arr.find(r=>r.date===date);if(x)vals.push(x)}if(!vals.length)continue;const close=median(vals.map(x=>x.close)),disagreementPct=vals.length>1?Math.max(...vals.map(x=>Math.abs(x.close/close-1))):0;if(disagreementPct>.08)continue;out.push({date,close,sourceCount:vals.length,disagreementPct,sources:vals.map(x=>x.source),anchorAt:vals.map(x=>x.anchorAt).sort().at(-1)})}return {rows:out,sourceHealth:{wallex:rs[0].status==='fulfilled',nobitex:rs[1].status==='fulfilled'},errors:rs.filter(x=>x.status==='rejected').map(x=>String(x.reason?.message||x.reason))}}

function normalizePublished(v){const s=String(v||''),m=s.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z$/);if(m)return `${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}Z`;const d=new Date(s);return Number.isFinite(d.getTime())?d.toISOString():null}
async function gdeltQuery(query,timespan='48h',maxrecords=75){const u=`https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(query)}&mode=ArtList&format=json&maxrecords=${maxrecords}&timespan=${timespan}&sort=DateDesc`;const r=await timeoutFetch(u,{},8000);if(!r.ok)throw new Error(`GDELT ${r.status}`);const j=await r.json();return (j.articles||[]).map(a=>({title:a.title,url:a.url,domain:a.domain||'',publishedAt:normalizePublished(a.seendate),description:'',source:'GDELT'})).filter(a=>a.publishedAt)}
async function googleNews(query,fa=false){const hl=fa?'fa':'en-US',gl=fa?'IR':'US',ceid=fa?'IR:fa':'US:en',u=`https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=${hl}&gl=${gl}&ceid=${ceid}`;const r=await timeoutFetch(u,{},7500);if(!r.ok)throw new Error(`Google News ${r.status}`);const xml=await r.text(),out=[];for(const m of xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)){const x=m[1],title=stripHtml(x.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||''),link=stripHtml(x.match(/<link>([\s\S]*?)<\/link>/i)?.[1]||''),pub=stripHtml(x.match(/<pubDate>([\s\S]*?)<\/pubDate>/i)?.[1]||''),src=stripHtml(x.match(/<source[^>]*>([\s\S]*?)<\/source>/i)?.[1]||'Google News'),publishedAt=normalizePublished(pub);if(title&&publishedAt)out.push({title,url:link,domain:src,publishedAt,description:'',source:fa?'Google News FA':'Google News EN'})}return out.slice(0,80)}
async function officialArticles(url,domain){const r=await timeoutFetch(url,{},8000);if(!r.ok)throw new Error(`${domain} ${r.status}`);const html=await r.text(),out=[];for(const m of html.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const title=stripHtml(m[2]);if(title.length<22||!/(iran|iranian|sanction|nuclear|middle east|treasury|ایران|هسته)/i.test(title))continue;const seg=stripHtml(html.slice(Math.max(0,(m.index||0)-500),Math.min(html.length,(m.index||0)+m[0].length+500))),dateText=seg.match(/(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+[0-3]?\d,\s+20\d{2}/i)?.[0],publishedAt=normalizePublished(dateText||'');if(!publishedAt)continue;let link=m[1];if(link.startsWith('/'))link=`https://${domain}${link}`;out.push({title,url:link,domain,publishedAt,description:'',source:'official'})}return out.slice(0,40)}
export async function semanticNewsScore(articles){const key=process.env.OPENAI_API_KEY;if(!key||!articles.length)return null;const model=process.env.OPENAI_NEWS_MODEL||'gpt-5.6-luna',compact=articles.slice(0,22).map((a,i)=>({id:i+1,title:a.title,domain:a.domain,publishedAt:a.publishedAt})),schema={type:'object',properties:{score:{type:'number',minimum:-1,maximum:1},confidence:{type:'number',minimum:0,maximum:1},reason:{type:'string'}},required:['score','confidence','reason'],additionalProperties:false};const body={model,input:[{role:'system',content:[{type:'input_text',text:'Estimate the next 24-48 hour directional effect of these deduplicated events on Iran free-market USD/Toman. +1 = upward USD/Toman pressure, -1 = downward pressure. Classify event impact, not generic sentiment. Avoid double counting. Stay near zero when evidence is mixed.'}]},{role:'user',content:[{type:'input_text',text:JSON.stringify(compact)}]}],text:{format:{type:'json_schema',name:'iran_fx_news_score',strict:true,schema}},max_output_tokens:220};const r=await timeoutFetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify(body)},11000);if(!r.ok)throw new Error(`OpenAI ${r.status}`);const j=await r.json();let txt='';for(const item of j.output||[])for(const c of item.content||[])if(c.type==='output_text')txt+=c.text||'';const o=JSON.parse(txt);return {score:clamp(o.score,-1,1),confidence:clamp(o.confidence,0,1),reason:String(o.reason||'').slice(0,300),model}}
async function cbiTelegramArticles(){const r=await timeoutFetch('https://t.me/s/prcbi1',{},7500);if(!r.ok)throw new Error(`CBI Telegram ${r.status}`);const html=await r.text(),out=[];for(const block of html.split(/tgme_widget_message_wrap/)){const dt=block.match(/datetime=["']([^"']+)/i)?.[1],publishedAt=normalizePublished(dt||'');if(!publishedAt)continue;const text=normalizeDigits(stripHtml(block)).replace(/\s+/g,' ').trim();if(text.length<20||!/(ارز|دلار|ریال|بازار ارز|اسکناس|صرافی|ذخایر|foreign exchange|currency|rial|dollar)/i.test(text))continue;const link=block.match(/href=["'](https:\/\/t\.me\/prcbi1\/\d+)["']/i)?.[1]||'https://t.me/s/prcbi1';out.push({title:text.slice(0,240),url:link,domain:'cbi.ir',publishedAt,description:text.slice(240,700),source:'CBI official Telegram'})}return out.slice(0,60)}
async function newsApiArticles(){const key=process.env.NEWSAPI_API_KEY;if(!key)return[];const q='Iran AND (rial OR currency OR sanctions OR nuclear OR central bank OR attack OR ceasefire)';const r=await timeoutFetch(`https://newsapi.org/v2/everything?q=${encodeURIComponent(q)}&sortBy=publishedAt&pageSize=100&apiKey=${encodeURIComponent(key)}`,{},8000);if(!r.ok)throw new Error(`NewsAPI ${r.status}`);const j=await r.json();return (j.articles||[]).map(a=>({title:a.title,url:a.url,domain:(()=>{try{return new URL(a.url).hostname.replace(/^www\./,'')}catch{return a.source?.name||''}})(),publishedAt:normalizePublished(a.publishedAt),description:a.description||'',source:'NewsAPI'})).filter(a=>a.publishedAt)}
export async function fetchNewsSignal({semantic=false}={}){const rs=await Promise.allSettled([gdeltQuery('(Iran OR Iranian) (rial OR currency OR forex OR "central bank" OR dollar)','48h',75),gdeltQuery('(Iran OR Iranian) (sanctions OR nuclear OR talks OR ceasefire OR attack OR missile OR war)','72h',100),googleNews('Iran rial sanctions nuclear central bank dollar',false),googleNews('ایران ریال دلار تحریم مذاکرات بانک مرکزی جنگ',true),officialArticles('https://ofac.treasury.gov/recent-actions','ofac.treasury.gov'),officialArticles('https://home.treasury.gov/news/press-releases','home.treasury.gov'),officialArticles('https://www.iaea.org/newscenter/focus/iran','iaea.org'),cbiTelegramArticles(),newsApiArticles()]);const arts=rs.flatMap(x=>x.status==='fulfilled'?x.value:[]);if(!arts.length)throw new Error('All news sources unavailable');const scored=scoreNews(arts);let semanticResult=null;if(semantic)try{semanticResult=await semanticNewsScore(scored.topEvents?.length?scored.topEvents:arts)}catch{}const blended=semanticResult?clamp(scored.score*.75+semanticResult.score*semanticResult.confidence*.25,-1,1):scored.score;return {...scored,score:blended,deterministicScore:scored.score,semantic:semanticResult,sourceHealth:{gdelt:rs[0].status==='fulfilled'||rs[1].status==='fulfilled',googleEN:rs[2].status==='fulfilled',googleFA:rs[3].status==='fulfilled',ofac:rs[4].status==='fulfilled',treasury:rs[5].status==='fulfilled',iaea:rs[6].status==='fulfilled',cbi:rs[7].status==='fulfilled',newsapi:rs[8].status==='fulfilled'&&!!process.env.NEWSAPI_API_KEY},source:'multi-source event engine'}}

async function stooqDaily(symbol){const r=await timeoutFetch(`https://stooq.com/q/l/?s=${encodeURIComponent(symbol)}&f=sd2t2ohlcv&h&e=csv`,{},6000);if(!r.ok)throw new Error(`Stooq ${r.status}`);const lines=(await r.text()).trim().split(/\r?\n/);if(lines.length<2)throw new Error('Stooq empty');const h=lines[0].split(','),v=lines[1].split(','),o={};h.forEach((k,i)=>o[k]=v[i]);const open=safeNum(o.Open),close=safeNum(o.Close);if(!open||!close)throw new Error('Stooq bad row');return {open,close,ret:close/open-1}}
export async function fetchMacroSignal(){const rs=await Promise.allSettled([stooqDaily('dx.f'),stooqDaily('xauusd'),stooqDaily('brn.f'),stooqDaily('eurusd')]),[dxy,gold,brent,eur]=rs.map(x=>x.status==='fulfilled'?x.value:null);if(!dxy&&!gold&&!brent&&!eur)throw new Error('All macro sources unavailable');return {score:Math.tanh((dxy?.ret||0)*18+(gold?.ret||0)*6+(brent?.ret||0)*2.5-(eur?.ret||0)*4),components:{dxy,gold,brent,eurusd:eur},source:'Stooq multi-macro'}}
export async function fetchAlphaMacro(){const key=process.env.ALPHA_VANTAGE_API_KEY;if(!key)return null;const q=async u=>{const r=await timeoutFetch(`https://www.alphavantage.co/query?${u}&apikey=${encodeURIComponent(key)}`,{},8500);if(!r.ok)throw new Error(`Alpha Vantage ${r.status}`);return r.json()};const rs=await Promise.allSettled([q('function=GOLD_SILVER_SPOT&symbol=GOLD'),q('function=BRENT&interval=daily'),q('function=TREASURY_YIELD&interval=daily&maturity=10year')]);return {gold:rs[0].status==='fulfilled'?rs[0].value:null,brent:rs[1].status==='fulfilled'?rs[1].value:null,treasury10y:rs[2].status==='fulfilled'?rs[2].value:null,available:rs.filter(x=>x.status==='fulfilled').length}}
export async function gatherAll({semanticNews=false}={}){const rs=await Promise.allSettled([fetchTGJUHistory('price_dollar_rl'),fetchTGJUHistory('price_aed'),fetchTGJUHistory('geram18'),fetchCurrentMarket(),fetchUSDTConsensus(),fetchNewsSignal({semantic:semanticNews}),fetchMacroSignal()]);if(rs[0].status!=='fulfilled')throw rs[0].reason;const val=i=>rs[i].status==='fulfilled'?rs[i].value:null;return {history:val(0),aedHistory:val(1),localGoldHistory:val(2),currentMarket:val(3),usdt:val(4),news:val(5),macro:val(6),health:{usdHistory:true,aedHistory:!!val(1),localGoldHistory:!!val(2),currentMarket:!!val(3),usdt:!!val(4),news:!!val(5),macro:!!val(6)},errors:rs.map((x,i)=>x.status==='rejected'?{index:i,message:String(x.reason?.message||x.reason)}:null).filter(Boolean)}}
